# Numpy exercise from w3 resouce

## 1-Numpy Basics

In [1]:
import numpy as np

In [2]:
# to show numpy version
print(np.__version__)

1.23.5


In [3]:
# to show numpy build configuration
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MosTa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MosTa/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MosTa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MosTa/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MosTa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MosTa/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MosTa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MosTa/anaconda3\\Lib

In [4]:
# get help with the 'add' function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
print(np.info(np.exp))

exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For oth

In [6]:
#test if none of elements in array is zero
a = np.array([1, 2, 3])
print(np.all(a))
b = np.array([0, 1, 2,23])
print(np.all(b))

True
False


In [7]:
# test if any of the elements are non-zero
a = np.array([1, 2, 3])
print(np.any(a))
b = np.array([0, 1, 2,23])
print(np.any(b))

True
True


In [8]:
# if element-wise is infinity or not a number (test for finiteness = means that each element is a finite number
a = np.array([1, 2, np.inf])
print(np.isfinite(a))
b = np.array([0, np.nan, 2,23])
print(np.isfinite(b))

[ True  True False]
[ True False  True  True]


In [9]:
# test for positive or negative infinity
a = np.array([1, 2, np.inf, np.nan, 45])
print(np.isinf(a))

[False False  True False False]


In [10]:
# check for NANs
a = np.array([1, 2, np.inf, np.nan, 45])
print(np.isnan(a))

[False False False  True False]


In [11]:
#check for complex # comples values uses letter "j " only
a = np.array([1, 2+5j, -2+8j, 4, 5])
print(np.iscomplex(a))
#check for real
a = np.array([1, 2+5j, -2+8j, 4, 5])
print(np.isreal(a))

#check for scalar numbers
a = np.array([1, 4, 5.4])
print(np.isscalar(a))

[False  True  True False False]
[ True False False  True  True]
False


In [12]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print original arr
print(a)
#Checking for complex number which is like 1+2j
print(np.iscomplex(a))
#Checking for real number which is like 1, 34
print(np.isreal(a))
#Checking for scalar type which means one item/ value
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
[ True False False False False  True]
[False  True  True  True  True False]
True
False


In [13]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print(x)
print(y)

#Comparison - if x element greater than y element
print(np.greater(x, y))

#Comparison if y element greater or equal to X element 
print(np.greater_equal(y, x))
#Comparison if Y ele  less than X ele
print(np.less(y, x))
#Comparison if X ele  less or equal to Y ele
print(np.less_equal(x, y))


[3 5]
[2 5]
[ True False]
[False  True]
[ True False]
[False  True]


11- Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [14]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(x)
print(y)

# Comparison if x  equal   y
print(np.equal(x, y))

#Comparison - if two arrays are almost closer 
print(np.allclose(x, y))


[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
[ True  True  True  True  True  True  True  True  True False]
True


12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [15]:
a = np.array([1, 7, 13, 105])
s = np.size(a)
print(a.size)
print(a.itemsize)# depend on the system item size will be 4bytes for int32
# if system allows to store an item in 64int, then item size will be 8 bytes
print((a.nbytes), "bytes" )
print((a.nbytes)*8,"bits")
#another approach
print(a.size*a.itemsize, "bytes")
print((a.size*a.itemsize)*8, "bits")

4
4
16 bytes
128 bits
16 bytes
128 bits


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [16]:
a = np.zeros((3, 10))
a


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
#slicing to replace 2nd row with 10 tens, & 3rd row with 10 fives
a[1, : ] = 10
a[2, : ] = 5
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.]])

In [18]:
a = np.zeros((10, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#slicing to replace 2nd column with 10 tens, & 3rd column with 10 fives
a[: , 1 ] = 10
a[: , 2 ] = 5
a

array([[ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.],
       [ 0., 10.,  5.]])

14.Write a NumPy program to create an array of integers from 30 to 70

In [20]:
a = np.arange(30,71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

15.Write a NumPy program to create an array of all even integers from 30 to 70

In [21]:
a= np.arange(30,71, 2)
a


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [22]:
# to create an array of all odd integers from 30 t0 70
a= np.arange(31,71, 2)
a

array([31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63,
       65, 67, 69])

16.Write a NumPy program to create a 3x3 identity matrix.

In [23]:
a = np.identity(3) # value means 3 by 3
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

17.Write a NumPy program to generate a random number between 0 and 1.

In [24]:
print(np.random.rand())

0.7427796528490335


18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [25]:
print(np.random.rand(15))

[0.21314976 0.22850707 0.14131588 0.59134856 0.97543254 0.14900413
 0.77349285 0.99486792 0.66769338 0.10656944 0.32255617 0.78521996
 0.51372059 0.50973438 0.22411052]


19.Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [26]:
a = np.arange(15,56)
aa = a[1: -1]
aa

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [27]:
a= np.linspace(5, 50, 10)
a

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [28]:
a = np.arange(0, 20)
print(a)
a[(a>=9) & (a<=15)] *= -1
print(a)
a = np.arange(0, 20)
a[9:16] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


23.Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [29]:
a = np.random.randint(0, 10, 5, dtype="int")
a

array([8, 9, 4, 3, 8])

24.Write a NumPy program to multiply the values of two given vectors

In [30]:
a= np.array([1, 2, 3, 4])
b= np.array([4, 3, 2, 1])
print(a*b)

[4 6 6 4]


25.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [31]:
a = np.arange(10,22).reshape((3,4))
a


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

26.Write a NumPy program to find the number of rows and columns in a given matrix

In [32]:
a = np.empty((5,7))
print(a.shape)

(5, 7)


27.Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0

In [33]:
a =np.eye(3)
a


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

28.Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [34]:
a = np.zeros((10,10))
a[0] =1
a[:, 0] =1
a[9] =1
a[:, 9] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

29.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [36]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

30.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [37]:
a = np.zeros((4,4))
a[0,1] =1
a[0,3] =1
a[1,0] =1
a[3,0] =1
a[2,1] =1
a[2,3] =1
a[3,2] =1
a

array([[0., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [38]:
x = np.zeros((4,4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

31.Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [39]:
a = np.random.random((3,3,3))
print(a)


[[[0.88048211 0.50040245 0.84999412]
  [0.82842902 0.85158124 0.13630351]
  [0.83061075 0.96524726 0.86366214]]

 [[0.83620201 0.39622884 0.68781166]
  [0.16626741 0.4333025  0.78660685]
  [0.89365238 0.65820106 0.33652012]]

 [[0.33926823 0.69028706 0.74165489]
  [0.51309768 0.63218207 0.31485671]
  [0.80262609 0.61522103 0.84827776]]]


In [40]:
a = np.random.randint(0, 27, 27, dtype= 'i4')
print(a)
b= a.reshape((3,3,3))
print(b)

[10  9  2  6 19 18  5 21 12 12 19  3 13 19 20 10  3 21 19  6 12  6  8 14
 15 26  6]
[[[10  9  2]
  [ 6 19 18]
  [ 5 21 12]]

 [[12 19  3]
  [13 19 20]
  [10  3 21]]

 [[19  6 12]
  [ 6  8 14]
  [15 26  6]]]


32.Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [41]:

print(np.cumsum(b))
print("______________________")
print(np.cumsum(b,axis =0))
print("______________________")
print(np.cumsum(b,axis =1))

[ 10  19  21  27  46  64  69  90 102 114 133 136 149 168 188 198 201 222
 241 247 259 265 273 287 302 328 334]
______________________
[[[10  9  2]
  [ 6 19 18]
  [ 5 21 12]]

 [[22 28  5]
  [19 38 38]
  [15 24 33]]

 [[41 34 17]
  [25 46 52]
  [30 50 39]]]
______________________
[[[10  9  2]
  [16 28 20]
  [21 49 32]]

 [[12 19  3]
  [25 38 23]
  [35 41 44]]

 [[19  6 12]
  [25 14 26]
  [40 40 32]]]


33.Write a NumPy program to compute the inner product of two given vectors

In [42]:
a = np.array([1,2,3,3])
b = np.array([2,3,1,1])
print(a.dot(b))

14


34. Write a NumPy program to add a vector to each row of a given matrix

In [43]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([[1, 1, 0], [1, 1, 0],[1, 1, 0],[1, 1, 0]])
m.shape

(4, 3)

In [44]:
mv = np.append(m, v, axis=1)
mv
mv.shape

(4, 6)

## 2-Numpy array

In [45]:
x = np.arange(2,6).reshape(2,2)
x

array([[2, 3],
       [4, 5]])

In [46]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
x= np.arange(1,28).reshape(3,3,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [48]:
print(np.__version__)

1.23.5


In [49]:
x = [12.23, 13.32, 100, 36.32]

a = np.array(x)
a

array([ 12.23,  13.32, 100.  ,  36.32])

In [50]:
a= np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [51]:
a = np.zeros(10)
a[6] =11
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [52]:
a= np.arange(12, 38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [53]:
# to print reverse of array a
a[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [54]:
x = np.asfarray(a)
x

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.])

In [55]:
x = np.ones((4, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
x[1:-1, 1:-1] =0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [57]:
x =np.array([[2,3,6],[3,4,7],[2,3,6],[3,4,7]])
x[0: ,0 ] = 0
x[0:, 2] =0
x[0] =0
x[3] =0
x

array([[0, 0, 0],
       [0, 4, 0],
       [0, 3, 0],
       [0, 0, 0]])

In [58]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
l = [1, 2, 3, 4, 5, 6, 7, 8]
print(np.asarray(l))
t = ([1,2,3,4],[1,2,3,4])
print(np.asarray(t))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [1 2 3 4]]


In [60]:
a= np.array([10, 20, 30])
b = np.append(a,[[40, 50, 60, 70,80, 90]])
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
x =np.empty((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
x =np.full((3,4), 44)
x

array([[44, 44, 44, 44],
       [44, 44, 44, 44],
       [44, 44, 44, 44]])

## 3-Linear Algebra

In [63]:
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])
print(q.dot(p))

[[1 2]
 [3 4]]


In [64]:
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])
print(np.outer(p,q, out=None))

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [65]:
from numpy import linalg as LA
a = np.array([[1, 0, 3], [1, 2, 4], [2, 3, 1]])
print(np.linalg.det(a))

-12.999999999999995


In [66]:
a= np.array([1,2,3])
b= np.array([2,3,4])
result =np.einsum("n,n", a, b)
print(result)

20


In [67]:
a = np.array([1,2,5])
b = np.array([2,1,0])
result = np.inner(a, b)
result

4

In [68]:
a = np.array([1,2,5])
b = np.array([2,1,0])
print(a.dot(b))

4


In [75]:
#matrix must be square
a = np.array([[1,2], [3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [77]:
#qr to get QR decomposition
m = np.array([[1,2],[3,4]])
print(np.linalg.qr(m))

(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [80]:
m = np.array([[1,2],[3,4]])
print(np.linalg.cond(m))

14.933034373659268


## 4-Mathematics

In [82]:
print(np.add(1.0, 4.0))

5.0


In [84]:
print(np.subtract(4.0, 1.0))

3.0


In [85]:
print(np.multiply(1, 4))

4


In [88]:
print(int(np.divide(4,2)))

2


In [89]:
#to get the powers of an array values element-wise
a= np.array([1,2,3])
print(np.power(a,3))

[ 1  8 27]


In [90]:
#to get the powers of an array values element-wise
a= np.array([8, 6,3])
print(np.remainder(a,3))

[2 0 0]


In [91]:
#to calculate the absolute value element-wise.
a=np.array([-1, -3, 4])
print(np.absolute(a))

[1 3 4]
